### ISSUE TITLE
notdhcpserver seems to be responding on the wrong vlan?

### ISSUE THREAD

**Issue by max-b** [sudomesh/notdhcpserver#7]
When I connect an extender node to one of the extender node ports on the homenode server (the one running notdhcpserver), it seems as though the notdhcpserver is sometimes responding on the wrong vlan interface:

```
root@my:~# notdhcpserver -vf -s /opt/notdhcpserver/hook.sh eth0.1=100.64.3.130/26 eth0.2=100.64.3.131/26
Verbose mode enabled
eth0.2: Physical connection detected
eth0.1: Received lease request
eth0.1: sending response (without ssl certificate)
eth0.1: Received lease request
eth0.1: sending response (without ssl certificate)
eth0.1: Received lease request
eth0.1: sending response (without ssl certificate)
eth0.1: Received lease request
eth0.1: sending response (without ssl certificate)
eth0.1: Received lease request
eth0.1: sending response (without ssl certificate)
```

You can see that the eth0.2 interface is the one that's actually been connected, but notdhcpserver is reporting that eth0.1 is where the lease request is coming from.

**Comment by Juul** [comment]
ah! i hadn't realized this, but it makes sense that a packet from 0.0.0.0 would be received by all interfaces on that layer 2 network. The simplest solution will be to respond on all physically connected interfaces that are in the correct state (which will usually only be one). I will try to implement that. I don't have a test-setup with me right now though.

**Comment by Juul** [comment]
hm, another necessary change will be for the ACK to contain the VLAN ID

**Comment by max-b** [comment]
So it seems that on my end 1e82cc8412013741e355616d7bf921533055c15d has fixed this issue. Because you've changed the size of the `struct request`, this is backwards incompatible with earlier versions of the notdhcpclient. 

We've made a lot of changes in the last week or so - we should expect that only the newest built versions of notdhcpclient and server will build.

Gonna go ahead and close for now.
