### ISSUE TITLE
notdhcpserver down hook doesn't run or fails before completing

### ISSUE THREAD

**Issue by Juul** [sudomesh/notdhcpserver#8]

**Comment by max-b** [comment]
Just running it from the command line I'm getting:

```
root@my:~# /opt/notdhcpserver/hook.sh down eth0.2 100.64.3.131
awk: bad regex ' *${PORT}t? *': Invalid content of \{\}
```

Edit: No that might be an older version of the hook. On a more recent version of the firmware/makenode combo, I'm getting:

```
root@my:~# /opt/notdhcpserver/hook.sh down eth0.1
Connect failed to /tmp/babeld.sock: No such file or directory
Are you sure you have a running babeld instance?
root@my:~# /opt/notdhcpserver/hook.sh down eth0.2
Connect failed to /tmp/babeld.sock: No such file or directory
Are you sure you have a running babeld instance?
```

Babel is definitely running. And that's the last line in hook script anyways.

**Comment by max-b** [comment]
I think the offending if call is at: https://github.com/sudomesh/notdhcp/blob/master/server.c#L497

I just got logs from a notdhcpserver node that had a disconnect:

```
Fri Sep  4 23:25:39 2015 daemon.warn notdhcpserver: eth0.1: Physical disconnect detected
```

But no corresponding hook call. Looks like maybe iface->state isn't getting set correctly when the original connection is made?

```
if(iface->state == STATE_GOT_ACK) {
```

**Comment by Juul** [comment]
Lines 225 an 231

**Comment by max-b** [comment]
Fixed
